import type { ApiContract } from './contracts'

export const apiRoutes: {
  [K in keyof ApiContract]: { [A in keyof ApiContract[K]]: string }
} = {
  auth: {
    wallet: '/v1/auth/wallet',
    me: '/v1/auth/me',
  },
  gigs: {
    list: '/v1/gigs',
    create: '/v1/gigs',
    get: '/v1/gigs/:id',
    update: '/v1/gigs/:id',
    delete: '/v1/gigs/:id',
    publish: '/v1/gigs/:id/publish',
    accept: '/v1/gigs/:id/accept',
    submit: '/v1/gigs/:id/submit',
    addProofs: '/v1/gigs/:id/proofs',
    approve: '/v1/gigs/:id/approve',
    dispute: '/v1/gigs/:id/dispute',
    resolve: '/v1/gigs/:id/resolve',
    refund: '/v1/gigs/:id/refund',
    review: '/v1/gigs/:id/review',
    transactions: '/v1/gigs/:id/transactions',
  },
  users: {
    get:            '/v1/users/:id',
    update:         '/v1/users/:id',
    gigs:           '/v1/users/:id/gigs',
    reviews:        '/v1/users/:id/reviews',
    transactions:   '/v1/users/:id/transactions',
    exchangeOffers: '/v1/users/:id/exchange',
  },
  upload: {
    signature: '/v1/upload/signature',
  },
  blockchain: {
    transaction:       '/v1/blockchain/transaction/:signature',
    createEscrow:      '/v1/blockchain/create-escrow',
    approveEscrow:     '/v1/blockchain/approve-escrow',
    cancelEscrow:      '/v1/blockchain/cancel-escrow',
    acceptGig:         '/v1/blockchain/accept-gig',
    submitProof:       '/v1/blockchain/submit-proof',
    refundExpired:     '/v1/blockchain/refund-expired',
    disputeGig:        '/v1/blockchain/dispute-gig',
    withdrawEarnings:  '/v1/blockchain/withdraw-earnings',
    createUserAccount: '/v1/blockchain/create-user-account',
  },
  platform: {
    config:        '/v1/platform/config',
    exchangeRates: '/v1/platform/exchange-rates',
  },
  conversations: {
    list:         '/v1/conversations',
    findOrCreate: '/v1/conversations',
    messages:     '/v1/conversations/:id/messages',
    sendMessage:  '/v1/conversations/:id/messages',
    close:        '/v1/conversations/:id/close',
  },
  notifications: {
    registerToken: '/v1/notifications/device-token',
  },
  subscriptions: {
    list:   '/v1/subscriptions',
    upsert: '/v1/subscriptions',
    remove: '/v1/subscriptions/:id',
  },
  reports: {
    create: '/v1/reports',
  },
  exchange: {
    list:    '/v1/exchange',
    create:  '/v1/exchange',
    get:     '/v1/exchange/:id',
    publish: '/v1/exchange/:id/publish',
    cancel:  '/v1/exchange/:id',
    accept:  '/v1/exchange/:id/accept',
    paid:    '/v1/exchange/:id/paid',
    confirm: '/v1/exchange/:id/confirm',
    dispute: '/v1/exchange/:id/dispute',
    resolve: '/v1/exchange/:id/resolve',
    refund:    '/v1/exchange/:id/refund',
    addProofs: '/v1/exchange/:id/proofs',
    review:    '/v1/exchange/:id/review',
    update:    '/v1/exchange/:id',
  },
  exchangeAccounts: {
    list:       '/v1/exchange/accounts',
    create:     '/v1/exchange/accounts',
    deactivate: '/v1/exchange/accounts/:id/deactivate',
  },
  exchangeBlockchain: {
    createEscrow: '/v1/blockchain/exchange-create-escrow',
    accept:       '/v1/blockchain/exchange-accept',
    submitProof:  '/v1/blockchain/exchange-submit-proof',
    confirm:      '/v1/blockchain/exchange-confirm',
    cancel:       '/v1/blockchain/exchange-cancel',
    dispute:      '/v1/blockchain/exchange-dispute',
    refund:       '/v1/blockchain/exchange-refund',
  },
}
