export { WorkspaceShell, type WorkspaceShellProps } from './WorkspaceShell'
export { WorkspacePage } from './WorkspacePage'
export { DetailPane, DetailEmpty, type DetailPaneProps } from './detail'
export * from './rail'
export * from './list'
