/**
 * Account SIZES, derived from the IDL rather than restated.
 *
 * Shared by BOTH harnesses on purpose. `tests-devnet/helpers.ts` carried its
 * own hand-computed copy of `PlatformState::LEN` and #27 shrank the struct by
 * 8 bytes — the copy kept the old number, so `ensurePlatform` decided a
 * freshly-migrated platform was "legacy", tried to close it, and every devnet
 * E2E died in its `before all` hook. A length that is typed out twice is a
 * length that will disagree with itself.
 *
 * The IDL is regenerated by `anchor build`, so anything derived here tracks
 * the Rust struct automatically. Deliberately dependency-free (no LiteSVM, no
 * web3) so the devnet harness can import it without pulling in the in-process
 * test runtime it exists to avoid.
 */
import IDL_JSON from "../target/idl/tenda_escrow.json";

/** Anchor's 8-byte account discriminator, ahead of every account's fields. */
const DISCRIMINATOR_BYTES = 8;

/** Fixed-width borsh primitives. Anything variable-length is refused below. */
const PRIMITIVE_BYTES: Readonly<Record<string, number>> = {
  bool: 1,
  u8: 1,
  i8: 1,
  u16: 2,
  i16: 2,
  u32: 4,
  i32: 4,
  u64: 8,
  i64: 8,
  u128: 16,
  i128: 16,
  pubkey: 32,
};

/**
 * Only the two shapes this module can size. Anything else — `defined` (a
 * referenced type), `option` (a tag byte plus a payload), a vector — reaches
 * `fieldBytes` as neither a string nor an array and is REFUSED there rather
 * than guessed at.
 */
type IdlType = string | { array?: [IdlType, number] };
interface IdlField {
  name: string;
  type: IdlType;
}
interface IdlTypeDef {
  name: string;
  type: { kind: string; fields?: IdlField[] };
}
interface IdlInstruction {
  name: string;
  accounts: Array<{ name: string }>;
}
/** One typed view of the document, so no reader re-asserts its shape inline. */
const IDL = IDL_JSON as {
  types?: IdlTypeDef[];
  instructions?: IdlInstruction[];
};

function fieldBytes(type: IdlType, path: string): number {
  if (typeof type === "string") {
    const size = PRIMITIVE_BYTES[type];
    if (size === undefined) {
      throw new Error(`${path}: no fixed size known for IDL type '${type}'`);
    }
    return size;
  }
  if (type.array !== undefined) {
    const [inner, count] = type.array;
    return fieldBytes(inner, `${path}[]`) * count;
  }
  // `option` adds a tag byte and `defined` needs the referenced type resolved.
  // Neither appears in PlatformState; refuse rather than guess a size.
  throw new Error(`${path}: unsupported IDL type ${JSON.stringify(type)}`);
}

/** The declared fields of a struct type, or a throw naming what was wrong. */
function structFields(name: string): IdlField[] {
  const def = (IDL.types ?? []).find((t) => t.name === name);
  if (def === undefined) throw new Error(`IDL type ${name} not found`);
  if (def.type.kind !== "struct" || def.type.fields === undefined) {
    throw new Error(`IDL type ${name} is not a struct`);
  }
  return def.type.fields;
}

/**
 * On-chain byte length of an Anchor account, discriminator included — the same
 * number the Rust `LEN` const declares and `close_legacy_platform` compares
 * against.
 */
export function idlAccountLen(name: string): number {
  return structFields(name).reduce(
    (total, field) => total + fieldBytes(field.type, `${name}.${field.name}`),
    DISCRIMINATOR_BYTES,
  );
}

/**
 * The account's field names, in declaration order.
 *
 * `idlAccountLen` follows the struct, so it can never pin the struct — a field
 * added back moves the length and everything derived from it moves with it.
 * The NAMES are what a test can hold still.
 */
export function idlAccountFields(name: string): string[] {
  return structFields(name).map((f) => f.name);
}

/**
 * The accounts an instruction declares, in order.
 *
 * This list IS the wire format: every caller — the server's transaction
 * builder included — reads it from the IDL, and every entry costs 32 bytes in
 * every transaction that uses the instruction. An account no constraint reads
 * is pure cost, so the list is worth holding still.
 */
export function idlInstructionAccounts(name: string): string[] {
  const ix = (IDL.instructions ?? []).find((i) => i.name === name);
  if (ix === undefined) throw new Error(`IDL instruction ${name} not found`);
  return ix.accounts.map((a) => a.name);
}

/** `PlatformState::LEN`. 133 before #27 removed the reserved `total_volume`. */
export const PLATFORM_STATE_LEN = idlAccountLen("PlatformState");
