export const ErrorCode = {
  // Auth
  INVALID_WALLET_ADDRESS:        'INVALID_WALLET_ADDRESS',
  INVALID_SIGNATURE:             'INVALID_SIGNATURE',
  UNAUTHORIZED:                  'UNAUTHORIZED',
  FORBIDDEN:                     'FORBIDDEN',
  // Users
  USER_NOT_FOUND:                'USER_NOT_FOUND',
  USER_SUSPENDED:                'USER_SUSPENDED',
  // Gigs
  GIG_NOT_FOUND:                 'GIG_NOT_FOUND',
  GIG_WRONG_STATUS:              'GIG_WRONG_STATUS',
  CANNOT_ACCEPT_OWN_GIG:         'CANNOT_ACCEPT_OWN_GIG',
  ACCEPT_DEADLINE_PASSED:        'ACCEPT_DEADLINE_PASSED',
  COMPLETION_DEADLINE_PASSED:    'COMPLETION_DEADLINE_PASSED',
  // Disputes / grace period
  DISPUTE_ALREADY_EXISTS:        'DISPUTE_ALREADY_EXISTS',
  GRACE_PERIOD_EXPIRED:          'GRACE_PERIOD_EXPIRED',
  // Reviews
  REVIEW_ALREADY_EXISTS:         'REVIEW_ALREADY_EXISTS',
  REVIEW_NOT_ALLOWED:            'REVIEW_NOT_ALLOWED',
  // Blockchain
  SIGNATURE_NOT_FINALIZED:       'SIGNATURE_NOT_FINALIZED',
  SIGNATURE_VERIFICATION_FAILED: 'SIGNATURE_VERIFICATION_FAILED',
  // Generic
  VALIDATION_ERROR:              'VALIDATION_ERROR',
  INTERNAL_ERROR:                'INTERNAL_ERROR',
} as const

export type ErrorCode = keyof typeof ErrorCode
