export const GIG_FEED_ACTIVE_RECOVERY_INTERVAL_MS = 120_000
export const GIG_FEED_IDLE_RECOVERY_INTERVAL_MS = 300_000
export const GIG_FEED_EMPTY_RECOVERY_LIMIT = 3
export const GIG_FEED_DEADLINE_RETRY_INTERVAL_MS = 30_000
