export {
  SUPPORT_FAQS,
  SUPPORT_GLOSSARY,
  SUPPORT_ESCROW_INTRO,
  SUPPORT_ESCROW_FLOW,
  SUPPORT_FEE_NOTE,
  SUPPORT_TOPICS,
  SUPPORT_GUIDE_POSTING,
  SUPPORT_GUIDE_WORKING,
  SUPPORT_WALLET_INTRO,
  SUPPORT_WALLET_GUIDE,
  SUPPORT_WALLET_TROUBLESHOOTING,
  type SupportFaq,
  type GlossaryTerm,
  type EscrowFlowStep,
  type SupportTopic,
  type GuideStep,
  type GuideSection,
  type WalletGuideEntry,
  type SupportQA,
} from './support'
